fn main() {
    tauri_build::build();

    // 自动发现 scripts/ 目录下所有 .sh 文件，生成 Rust 模块
    // 这样新增脚本只需放到 scripts/ 下，无需修改 Rust 代码。
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap(); // = src-tauri/
    let scripts_dir = std::path::Path::new(&manifest_dir)
        .join("..")
        .join("scripts");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir).join("generated_scripts.rs");

    // 收集所有 .sh 文件，按文件名排序保证确定性
    let mut entries: Vec<(String, std::path::PathBuf)> = Vec::new();
    if let Ok(read_dir) = std::fs::read_dir(&scripts_dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.is_file()
                && path.extension().map_or(false, |ext| ext == "sh")
            {
                let name = path.file_name().unwrap().to_string_lossy().to_string();
                entries.push((name, path));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // 生成 Rust 源代码
    // 使用 include_str! + env!("CARGO_MANIFEST_DIR") 构造绝对路径，
    // 避免内容转义问题，且 Cargo 能正确跟踪文件依赖。
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — DO NOT EDIT\n");
    code.push_str("// 每次 scripts/ 下 .sh 文件变更时自动重新生成。\n\n");

    // all_scripts() — 返回所有 (文件名, 内容) 对
    code.push_str("pub fn all_scripts() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");
    for (name, _) in &entries {
        code.push_str(&format!(
            "        ({:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../scripts/{}\"))),\n",
            name, name
        ));
    }
    code.push_str("    ]\n");
    code.push_str("}\n\n");

    // get_script(name) — 按文件名查找单个脚本
    code.push_str("pub fn get_script(name: &str) -> Option<&'static str> {\n");
    code.push_str("    match name {\n");
    for (name, _) in &entries {
        code.push_str(&format!(
            "        {:?} => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../scripts/{}\"))),\n",
            name, name
        ));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    std::fs::write(&out_path, code).unwrap();
    eprintln!("generated_scripts.rs: {} entries", entries.len());

    // 告知 Cargo：当 scripts/ 目录下任何文件变化时重新运行 build.rs
    println!("cargo:rerun-if-changed={}", scripts_dir.display());
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}